
package com.gagan.jaxws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlanetSoapServiceImplService", targetNamespace = "http://soap.service.gagan.com/", wsdlLocation = "http://localhost:9090/planetService?wsdl")
public class PlanetSoapServiceImplService
    extends Service
{

    private final static URL PLANETSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLANETSOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PLANETSOAPSERVICEIMPLSERVICE_QNAME = new QName("http://soap.service.gagan.com/", "PlanetSoapServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/planetService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLANETSOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PLANETSOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PlanetSoapServiceImplService() {
        super(__getWsdlLocation(), PLANETSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public PlanetSoapServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLANETSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public PlanetSoapServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PLANETSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public PlanetSoapServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLANETSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public PlanetSoapServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlanetSoapServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PlanetSoapService
     */
    @WebEndpoint(name = "PlanetSoapServiceImplPort")
    public PlanetSoapService getPlanetSoapServiceImplPort() {
        return super.getPort(new QName("http://soap.service.gagan.com/", "PlanetSoapServiceImplPort"), PlanetSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlanetSoapService
     */
    @WebEndpoint(name = "PlanetSoapServiceImplPort")
    public PlanetSoapService getPlanetSoapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service.gagan.com/", "PlanetSoapServiceImplPort"), PlanetSoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLANETSOAPSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PLANETSOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PLANETSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
